{% set name = "markdownlint-cli" %}
{% set version = "0.48.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/igorshubovych/markdownlint-cli/archive/refs/tags/v{{ version }}.tar.gz
  sha256: bdb0d744d3d94c0207ad93823508071ae9ca2ae61fed31a70cc086c9678ae8a4

build:
  number: 0

requirements:
  build:
    - nodejs  # [unix]
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

test:
  commands:
    - markdownlint --help

about:
  home: https://github.com/igorshubovych/markdownlint-cli
  license: MIT
  license_file: LICENSE
  summary: 'MarkdownLint Command Line Interface'

extra:
  recipe-maintainers:
    - timostrunk
    - dennis-wey
