{% set name = "markdownlint-cli" %}
{% set version = "0.43.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/igorshubovych/markdownlint-cli/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9d9e5ac88a9abce2a06889c5e754497a1d3dcad0334baac59ecea36a99003c1d

build:
  number: 0

requirements:
  build:
    - nodejs  # [unix]
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

test:
  commands:
    - markdownlint --help

about:
  home: https://github.com/igorshubovych/markdownlint-cli
  license: MIT
  license_file: LICENSE
  summary: 'MarkdownLint Command Line Interface'

extra:
  recipe-maintainers:
    - timostrunk
    - dennis-wey
