{% set name = "markdownlint-cli" %}
{% set version = "0.42.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/igorshubovych/markdownlint-cli/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 47e918b2f82deee662fa087fbdab591fb5e50c5fbc7a8fff2b73471cc865c2e1

build:
  number: 0

requirements:
  build:
    - nodejs  # [unix]
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

test:
  commands:
    - markdownlint --help

about:
  home: https://github.com/igorshubovych/markdownlint-cli
  license: MIT
  license_file: LICENSE
  summary: 'MarkdownLint Command Line Interface'

extra:
  recipe-maintainers:
    - timostrunk
    - dennis-wey
