{% set name = "markdownlint-cli" %}
{% set version = "0.49.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/igorshubovych/markdownlint-cli/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8e50b7e14b24774058898c7bbefe2f09ae0393161f8d6cd70824c57fd175cd9b

build:
  number: 0

requirements:
  build:
    - nodejs  # [unix]
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

test:
  commands:
    - markdownlint --help

about:
  home: https://github.com/igorshubovych/markdownlint-cli
  license: MIT
  license_file: LICENSE
  summary: 'MarkdownLint Command Line Interface'

extra:
  recipe-maintainers:
    - timostrunk
    - dennis-wey
