{% set name = "markdownlint-cli" %}
{% set version = "0.46.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/igorshubovych/markdownlint-cli/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b8a2521c59bb18037f5433ae19f14cce71c770d7bce50521182700fcbf43b4d6

build:
  number: 0

requirements:
  build:
    - nodejs  # [unix]
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

test:
  commands:
    - markdownlint --help

about:
  home: https://github.com/igorshubovych/markdownlint-cli
  license: MIT
  license_file: LICENSE
  summary: 'MarkdownLint Command Line Interface'

extra:
  recipe-maintainers:
    - timostrunk
    - dennis-wey
